/**
 * Global Constants & Configurations
 */

export const APP_INFO = {
  TITLE: 'VISHAL MEGA MART',
  VERSION: '3.4',
  COMPANY: 'Markss Infotech Ltd',
  DEVELOPER: 'TeCMi Vyapti',
  DEFAULT_YEAR: new Date().getFullYear()
};

export const API_DEFAULTS = {
  PAGE_INDEX: 1,
  PAGE_SIZE: 100,
  USER_ID: '26', // Hardcoded for now, to be replaced by auth context in Phase 3
  SORT_COLUMN: 'STORE',
  SORT_DIRECTION: 'asc'
};

export const USE_GLOBAL_MOCK_DATA = false;

export const STORE_MAPPING = {
  "HD02": "PITAMPURA",
  "HD24": "NAJAFGARH-2",
  "HD28": "NEB SARAI",
  "HD32": "ROHINI",
  "HD47": "PUL PRAHLADPUR",
  "HD49": "RAJOURI GARDEN-2",
  "HH10": "FARIDABAD",
  "HH32": "GURGAON-5-RAILWAY ROAD",
  "HH35": "MANESAR",
  "HD12": "TILAK NAGAR",
  "HH26": "BADSHAHPUR",
  "HH15": "DUNDEHERA",
  "HD14": "UTTAM NAGAR",
  "HD37": "KIRARI",
  "HD06": "MAHIPALPUR",
  "HD15": "NARELA",
  "HD16": "NANGLOI",
  "HD30": "BADARPUR",
  "HH02": "GURGAON",
  "HH27": "GURGAON-2-KHANDSA RD",
  "HD17": "SHAHDRA",
  "HD31": "MAHAVIR ENCLAVE",
  "HD26": "BURARI",
  "HD38": "NAJAFGARH-3",
  "ED06": "VIKAS PURI",
  "HD40": "KARAWAL NAGAR",
  "HD27": "MANGOLPURI",
  "HD41": "CHATTARPUR-DELHI",
  "HD23": "DEVLI-ROAD",
  "HD25": "GOVIND PURI",
  "HD44": "UTTAMNAGAR-2",
  "HD50": "BHOLA NATH",
  "HD39": "SAGARPUR",
  "HD43": "KHIRKI EXTENSION",
  "HD48": "BINDAPUR-2",
  "HD51": "NIHAL VIHAR",
  "HH34": "SOHNA",
  "HH38": "GURGAON PATAUDI",
  "HD55": "DWARKA PALAM EXTN",
  "HD56": "PATEL NAGAR",
  "HD57": "ROHINI SEC-3",
  "HH40": "GURGAON SEC-89",
  "HH43": "GURGAON SEC 102",
  "HD58": "SHAHDRA VIKAS CINE MALL",
  "HH45": "GURGAON SEC-92",
  "HH51": "MALL OFFARIDABAD"
};